### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by SATYAJIT1910** [aghosh0605/Coconut_Cutter-RUDRA#1]
It is suggested from my end to include a [docker ](https://www.docker.com/)image of this project in GitHub.

**Comment by ghoshzsh** [comment]
It will be published within today😋. Thanks for suggesting the isse.☺

**Comment by ghoshzsh** [comment]
Please clone the new repo and you will get the Docker Files. Readme also created for docker documentation. Thank you ☺
